[package]
name = "rr"
version = "0.1.0"
authors = ["David Hedgren <david@hedgren.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
async-std = {version = "1"}